### ISSUE TITLE
select2 add-another implementation

### ISSUE THREAD

**Issue by novitzkas** [jonashaag/django-addanother#13] opened 2016-05-31 08:58 UTC
Hi,

Thanks for the app, its coming together nicely. 

I am trying to integrate with select2 using the Select2AddAnother widget and its works to a certain degree.

Only issue i have is that when i add another instance and the pop-up window closes the option is selected, but not set as initial using select2 in my form.

Any ideas on this one? 

Thanks guys!

**Comment by jonashaag** [comment] 2016-05-31 12:02
> Only issue i have is that when i add another instance and the pop-up window closes the option is selected, but not set as initial using select2 in my form.

Not sure what you mean by "not set as initial"? Maybe a screen shot could help.

**Comment by novitzkas** [comment] 2016-05-31 12:24
Thanks for replying Jonas. Apologies for being a little vague. So what i mean is that after the pop-up closes and the instance is created, the option that should be selected does not display. But if i check the select2 dropdown, the newly created instance is in the list and marked as selected if i inspect the debug. Hope this makes more sense...

I have attached some screenshots of what i have and what I'm trying to achieve.

Thanks!

![after_popup_instance_create](https://cloud.githubusercontent.com/assets/18260221/15674119/4ef0e5fe-273b-11e6-8f73-4140252345cb.png)
![selected_dropdown](https://cloud.githubusercontent.com/assets/18260221/15674120/4ef6bab0-273b-11e6-8a9b-f0f92df4b192.png)
![expected_result](https://cloud.githubusercontent.com/assets/18260221/15674121/4efd6932-273b-11e6-899d-2366212afc0a.png)

**Comment by jonashaag** [comment] 2016-05-31 12:46
Interesting. Maybe we miss to trigger some events that select2 needs...

**Comment by jonashaag** [comment] 2016-05-31 12:46
Could you try doing a manual `$("#your_select").trigger("change")` after closing the popup?

**Comment by novitzkas** [comment] 2016-05-31 12:53
I thought about doing the .trigger("change") , the problem i have is the select is inside a modal...not sure where i can initiate the trigger after the popup closes...

**Comment by novitzkas** [comment] 2016-05-31 12:54
I will give it a try though, thanks!

**Comment by jonashaag** [comment] 2016-05-31 13:40
@novitzkas I meant that more as a means to debug if the missing event is the root cause in the first place. If it turns out to be the problem we can fix it in django-addanother.

**Comment by novitzkas** [comment] 2016-05-31 13:43
So i have tried this and after the popup window closes, i am able to get the required result with a $("#select").trigger("change"). Although sometimes it works and sometimes it doesn't, i assume this is a timing issue when the popup closes and "reloads" the parent.

**Comment by jonashaag** [comment] 2016-05-31 13:47
Thanks! The root cause probably is in Django's JavaScript then; it misses firing the `change` signal. You can test that by adding an event listener to a vanilla add-another field in the Django admin (without this app) and seeing if it is invoked when you add a new instance.

**Comment by novitzkas** [comment] 2016-05-31 14:44
No problem. I tried to replicate again, but my results are a little inconsistent and chrome is also not playing nice with trigger("change"). 

If you do fix this in django-addanother, please let me know....

Thanks Jonas.

**Comment by jpic** [comment] 2016-06-01 12:13
django-autocomplete-light provides a patch for this, perhaps you should try
it.

**Comment by jonashaag** [comment] 2016-06-01 14:32
Can we copy that fix to this project?

**Comment by jpic** [comment] 2016-06-03 01:26
There's a PR in select2 for this, it'll be in select2 soon, but yes of course it's opensource :)

**Comment by jonashaag** [comment] 2016-06-03 06:22
Haven't found it, could you provide a link?

**Comment by jpic** [comment] 2016-06-03 06:25
https://github.com/yourlabs/django-autocomplete-light/blob/master/src/dal_select2/static/autocomplete_light/select2.js#L92-L98
​

**Comment by jonashaag** [comment] 2016-06-03 06:59
https://github.com/select2/select2/commit/ea79a197e0ffe55aa600eed6d18cbd1c804c3176

Now all we have to do is wait for a release :)

@novitzkas could you try with the bleeding edge version of select2?

**Comment by jonashaag** [comment] 2016-06-15 18:41
This is now released in select2 4.0.3

**Closed as completed by jonashaag** 2016-06-15 18:41 UTC
